// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Youtube.Infrastructure.Data;

#nullable disable

namespace Youtube.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240503162957_AddYoutuberRecords")]
    partial class AddYoutuberRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Youtube.Domain.Entities.Youtuber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Joined")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Subscribers")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("videos")
                        .HasColumnType("int");

                    b.Property<int>("views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Youtubers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Joined = new DateTime(2024, 5, 3, 17, 29, 57, 50, DateTimeKind.Local).AddTicks(5784),
                            Name = "Wuant",
                            Subscribers = 3690000,
                            country = "Portugal",
                            videos = 1596,
                            views = 1342325614
                        },
                        new
                        {
                            Id = 2,
                            Joined = new DateTime(2024, 5, 3, 17, 29, 57, 50, DateTimeKind.Local).AddTicks(5842),
                            Name = "Toshiruz",
                            Subscribers = 616000,
                            country = "Brazil",
                            videos = 1482,
                            views = 124672906
                        },
                        new
                        {
                            Id = 3,
                            Joined = new DateTime(2024, 5, 3, 17, 29, 57, 50, DateTimeKind.Local).AddTicks(5845),
                            Name = "Wuant",
                            Subscribers = 111000000,
                            country = "Sweden",
                            videos = 4760,
                            views = 292766664
                        });
                });

            modelBuilder.Entity("Youtube.Domain.Entities.YoutuberRecords", b =>
                {
                    b.Property<int>("Youtuber_Trophy")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YoutuberId")
                        .HasColumnType("int");

                    b.HasKey("Youtuber_Trophy");

                    b.HasIndex("YoutuberId");

                    b.ToTable("YoutuberRecords");

                    b.HasData(
                        new
                        {
                            Youtuber_Trophy = 100000,
                            SpecialDetails = "Some special details for this record",
                            YoutuberId = 1
                        },
                        new
                        {
                            Youtuber_Trophy = 1000000,
                            SpecialDetails = "Some special details for this record",
                            YoutuberId = 1
                        },
                        new
                        {
                            Youtuber_Trophy = 100001,
                            SpecialDetails = "Some special details for this record",
                            YoutuberId = 2
                        },
                        new
                        {
                            Youtuber_Trophy = 100002,
                            SpecialDetails = "Some special details for this record",
                            YoutuberId = 3
                        },
                        new
                        {
                            Youtuber_Trophy = 100005,
                            SpecialDetails = "Some special details for this record",
                            YoutuberId = 3
                        },
                        new
                        {
                            Youtuber_Trophy = 10000000,
                            SpecialDetails = "Some special details for this record",
                            YoutuberId = 3
                        },
                        new
                        {
                            Youtuber_Trophy = 50000000,
                            SpecialDetails = "Some special details for this record",
                            YoutuberId = 3
                        });
                });

            modelBuilder.Entity("Youtube.Domain.Entities.YoutuberRecords", b =>
                {
                    b.HasOne("Youtube.Domain.Entities.Youtuber", "Youtuber")
                        .WithMany()
                        .HasForeignKey("YoutuberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Youtuber");
                });
#pragma warning restore 612, 618
        }
    }
}
